package djf.settings;

/**
 * This enum provides properties that are to be loaded via
 * XML files to be used for setting up the application.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum AppPropertyType {
    // LOADED FROM app_properties.xml

    // INITIAL WINDOW TITLE AND LOGO
    APP_TITLE,
    APP_LOGO,
    APP_ICON,

    // INITIAL WINDOW GEOMETRY
    PREF_WIDTH,
    PREF_HEIGHT,
    START_MAXIMIZED,
    DEFAULT_NODE_X,
    DEFAULT_NODE_Y,
    
    // FOR FINDING THE CSS FILE
    APP_CSS,
    APP_PATH_CSS,

    // FILE TOOLBAR ICONS
    NEW_ICON,
    LOAD_ICON,
    SAVE_ICON,
    SAVE_AS_ICON,
    EXIT_ICON,
    
    // EDIT TOOLBAR ICONS
    ADD_ICON,
    REMOVE_ICON,
    LIST_ICON,
    ROTATE_ICON,
    FIND_ICON,
    BOLD_ICON,
    ITALICS_ICON,
    ZOOMIN_ICON,
    ZOOMOUT_ICON,
    INC_ICON,
    DEC_ICON,
        
    // FILE TOOLBAR TOOLTIPS FOR BUTTONS
    NEW_TOOLTIP,
    LOAD_TOOLTIP,
    SAVE_TOOLTIP,
    SAVE_AS_TOOLTIP,
    EXPORT_TOOLTIP,
    UNDO_TOOLTIP,
    REDO_TOOLTIP,
    ABOUT_TOOLTIP,
    
    // EDIT TOOLBAR TOOLTIPS
    LINE_EDITOR_TOOLTIP,
    ADD_LINE_TOOLTIP,
    REMOVE_LINE_TOOLTIP,
    ADD_STATION_ON_LINE_TOOLTIP,
    REMOVE_STATION_FROM_LINE_TOOLTIP,
    LIST_TOOLTIP,
    THICKNESS_SLIDER_TOOLTIP,
    
    ADD_STATION_TOOLTIP,
    REMOVE_STATION_TOOLTIP,
    SNAP_TOOLTIP,
    MOVE_LABEL_TOOLTIP,
    ROTATE_TOOLTIP,
    RADIUS_SLIDER_TOOLTIP,
    
    FIND_TOOLTIP,
    
    IMAGE_BACKGROUND_TOOLTIP,
    ADD_IMAGE_TOOLTIP,
    ADD_LABEL_TOOLTIP,
    REMOVE_ELEMENT_TOOLTOP,
    
    BOLD_TOOLTIP,
    ITALICS_TOOLTIP,
    
    ZOOMIN_TOOLTIP,
    ZOOMOUT_TOOLTIP,
    INC_TOOLTIP,
    DEC_TOOLTIP,    
	
    // ERROR MESSAGES AND TITLES FOR DIALOG BOXES
    NEW_ERROR_MESSAGE,
    NEW_ERROR_TITLE,
    LOAD_ERROR_MESSAGE,
    LOAD_ERROR_TITLE,
    SAVE_ERROR_MESSAGE,
    SAVE_ERROR_TITLE,
    PROPERTIES_LOAD_ERROR_MESSAGE,
    PROPERTIES_LOAD_ERROR_TITLE,
	
    // AND VERIFICATION MESSAGES AND TITLES
    NEW_COMPLETED_MESSAGE,
    NEW_COMPLETED_TITLE,
    LOAD_COMPLETED_MESSAGE,
    LOAD_COMPLETED_TITLE,
    SAVE_COMPLETED_MESSAGE,
    SAVE_COMPLETED_TITLE,	
    SAVE_UNSAVED_WORK_TITLE,
    SAVE_UNSAVED_WORK_MESSAGE,
    SAVE_WORK_TITLE,
    LOAD_WORK_TITLE,

    // DATA FILE EXTENSIONS AND DESSCRIPTIONS
    WORK_FILE_EXT,
    WORK_FILE_EXT_DESC
}
